#!/bin/bash

EXEC=""
TARGET="buildScript"
PARAMS=()

for e in "$@"; do
  TARGET="$TARGET/$e"
  PARAMS+=("$e")
  if [ -x "${TARGET}.sh" ]; then
    EXEC="${TARGET}.sh"
    PARAMS=()
  fi
done

echo ">> $EXEC"
exec "$EXEC" "${PARAMS[@]}"
